requires = ["tox>=4"]
env_list = ["lint", "type", "3.13", "3.12", "3.11"]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest>=8",
    "pytest-sugar",
    "pytest-cov"
]
commands = [["pytest", { replace = "posargs", default = ["test.py",
                                                         "--cov-branch", 
                                                         "--cov-report=term-missing",
                                                         "--cov=sample"], extend = true }]]

[env.lint]
description = "run linters"
skip_install = true
deps = ["black"]
commands = [["black", { replace = "posargs", default = ["."], extend = true} ]]

[env.type]
description = "run type checks"
deps = ["mypy"]
commands = [["mypy", { replace = "posargs", default = [".", 
                                                       "--ignore-missing-imports"], extend = true} ]]
