name: ci-cd

on:
  # Triggers the workflow on push or pull request events but only for 
  # the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Package directory is not the root of the repository
# so working-directory is set
defaults:
  run:
    working-directory: practices/code/package-demo

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest
    
    # Define job steps
    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install poetry
      uses: snok/install-poetry@v1.4

    - name: Install package and its dependencies
      run: |
        poetry install --no-interaction --no-root

    - name: Run tests
      run: |
        poetry run tox run --parallel all

    - name: Build documentation
      run: poetry run make html --directory docs/
  cd:
    permissions:
      id-token: write
      contents: write
    
    # Only run this job if the "ci" job passes
    needs: ci

    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: steps.release.outputs.released == 'true'
      with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    
    - name: Test install from TestPyPI
      run: |
              pip install \
              --index-url https://test.pypi.org/simple/ \
              package-demo